apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-web
  namespace: data-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: kindservices/datamesh-dashboard-web:latest-build
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-web
  namespace: data-mesh
spec:
  type: LoadBalancer
  sessionAffinity: None
  selector:
    app: dashboard-web
  ports:
  - name : default
    port: 80
    targetPort: 3000