name: Build Server

on:
  push:
    branches:
      - main
      - dev
      - aaron

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - uses: coursier/cache-action@v6.3
    - uses: VirtusLab/scala-cli-setup@v0.1
    - name: Scalafmt check
      working-directory: ./server
      run: |
        scala-cli fmt --check . || (
          echo "To format code run"
          echo "  scala-cli fmt ."
          exit 1
        )
    - name: Build
      working-directory: ./server
      run: | 
      
        export BUILD_NUMBER=${{github.run_number}}
        make build

        docker use --load
        
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 

        make push
    - name: Logout from Docker Hub
      run: docker logout
