run: buildDocker
	source ./build.sh && run
dev:
	source ./build.sh && dev
buildDocker: 
	source ./build.sh && buildDocker
push: buildDocker
	source ./build.sh && push
installArgo:
	source ./build.sh && installArgo
