run: buildDocker
	source ./build.sh && run
runLocal:
	source ./build.sh && runLocal
buildDocker: 
	source ./build.sh && buildDocker
push: buildDocker
	source ./build.sh && push
installArgo:
	source ./build.sh && installArgo
